const express=require("express")
const bodyparser=require("body-parser")
const routes=require("./src/config/routes")
const cors = require ('cors')
var app=express()
app.use(cors({origin:"*"}))
app.use(bodyparser.urlencoded({extended:false}))
app.use(bodyparser.json())
app.use("/",routes.routes)
app.listen(3000)